-- Extension needed for UUID generation (used by aggregates and volume_windows tables)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Tables are now created per-symbol automatically by TradeDAO.ensureTables(symbol)
-- No static global tables needed.
-- Table naming pattern: {type}_{symbol_lowercase}
--   raw_trades_btcusdt, raw_trades_ethusdt, ...
--   aggregates_btcusdt, aggregates_ethusdt, ...
--   filtered_trades_btcusdt, filtered_trades_ethusdt, ...
--   volume_windows_btcusdt, volume_windows_ethusdt, ...
